-- Script de création de schéma pour Oracle
-- Cible : DSN/Schema "SummerClub" (utilisateur SOUMAYA dans connection.cpp)
-- Tester/exécuter ce script avec un compte ayant les droits de création ou depuis l'utilisateur SOUMAYA.

-- NOTE: Ce script utilise des SEQUENCE + TRIGGER pour générer les PK.
-- Si vous utilisez Oracle 12c+, vous pouvez remplacer par GENERATED AS IDENTITY si vous préférez.

-- 1) Table EMPLOYES
CREATE TABLE EMPLOYES (
    ID_EMPLOYE NUMBER NOT NULL,
    NOM        VARCHAR2(20 BYTE),
    PRENOM     VARCHAR2(20 BYTE),
    POSTE      VARCHAR2(20 BYTE),
    CONTRAT    VARCHAR2(20 BYTE),
    SALAIRE    NUMBER,
    CONSTRAINT EMPLOYES_PK PRIMARY KEY (ID_EMPLOYE)
);

CREATE SEQUENCE EMPLOYES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER EMPLOYES_BI
BEFORE INSERT ON EMPLOYES
FOR EACH ROW
WHEN (NEW.ID_EMPLOYE IS NULL)
BEGIN
  SELECT EMPLOYES_SEQ.NEXTVAL INTO :NEW.ID_EMPLOYE FROM DUAL;
END;
/

-- 2) Table EVENEMENT
CREATE TABLE EVENEMENT (
    ID_EVENT       NUMBER NOT NULL,
    LIEUX          VARCHAR2(20 BYTE),
    DATE_EVENT     DATE,
    TYPE_EV        NVARCHAR2(20),
    CONFIDENTIALITE VARCHAR2(20 BYTE),
    RESPONSABLE    VARCHAR2(20 BYTE),
    CAPACITE       NUMBER,
    ID_EMPLOYE     NUMBER,
    CONSTRAINT EVENEMENT_PK PRIMARY KEY (ID_EVENT),
    CONSTRAINT EVENEMENT_FK_EMP FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYES (ID_EMPLOYE)
);

CREATE SEQUENCE EVENEMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER EVENEMENT_BI
BEFORE INSERT ON EVENEMENT
FOR EACH ROW
WHEN (NEW.ID_EVENT IS NULL)
BEGIN
  SELECT EVENEMENT_SEQ.NEXTVAL INTO :NEW.ID_EVENT FROM DUAL;
END;
/

-- 3) Table FOURNISSEUR (correspond aux colonnes visibles dans l'UI)
CREATE TABLE FOURNISSEUR (
    ID_FOURNISSEUR NUMBER NOT NULL,
    NOM             VARCHAR2(100 BYTE),
    DOMAINE         VARCHAR2(100 BYTE),
    PRODUIT         VARCHAR2(200 BYTE),
    ADRESSE         VARCHAR2(200 BYTE),
    TEL             VARCHAR2(50 BYTE),
    EMAIL           VARCHAR2(100 BYTE),
    CONSTRAINT FOURNISSEUR_PK PRIMARY KEY (ID_FOURNISSEUR)
);

CREATE SEQUENCE FOURNISSEUR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER FOURNISSEUR_BI
BEFORE INSERT ON FOURNISSEUR
FOR EACH ROW
WHEN (NEW.ID_FOURNISSEUR IS NULL)
BEGIN
  SELECT FOURNISSEUR_SEQ.NEXTVAL INTO :NEW.ID_FOURNISSEUR FROM DUAL;
END;
/

-- 4) Table ACTIVITES (squelette, adapter selon besoins)
CREATE TABLE ACTIVITES (
    ID_ACTIVITE NUMBER NOT NULL,
    NOM_ACTIVITE VARCHAR2(100 BYTE),
    DESCRIPTION  VARCHAR2(4000 BYTE),
    CONSTRAINT ACTIVITES_PK PRIMARY KEY (ID_ACTIVITE)
);

CREATE SEQUENCE ACTIVITES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER ACTIVITES_BI
BEFORE INSERT ON ACTIVITES
FOR EACH ROW
WHEN (NEW.ID_ACTIVITE IS NULL)
BEGIN
  SELECT ACTIVITES_SEQ.NEXTVAL INTO :NEW.ID_ACTIVITE FROM DUAL;
END;
/

-- 5) Table INSCRIPTION (ex: lien entre enfant/utilisateur et evenement)
CREATE TABLE INSCRIPTION (
    ID_INSCRIPTION NUMBER NOT NULL,
    ID_EVENT       NUMBER NOT NULL,
    PARTICIPANT    VARCHAR2(200 BYTE),
    DATE_INSCR     DATE,
    CONSTRAINT INSCRIPTION_PK PRIMARY KEY (ID_INSCRIPTION),
    CONSTRAINT INSCRIPTION_FK_EVENT FOREIGN KEY (ID_EVENT) REFERENCES EVENEMENT(ID_EVENT)
);

CREATE SEQUENCE INSCRIPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER INSCRIPTION_BI
BEFORE INSERT ON INSCRIPTION
FOR EACH ROW
WHEN (NEW.ID_INSCRIPTION IS NULL)
BEGIN
  SELECT INSCRIPTION_SEQ.NEXTVAL INTO :NEW.ID_INSCRIPTION FROM DUAL;
END;
/

-- 6) Table PLANNING (squelette)
CREATE TABLE PLANNING (
    ID_PLANNING NUMBER NOT NULL,
    ID_EVENT    NUMBER,
    DATE_DEB    DATE,
    DATE_FIN    DATE,
    CONSTRAINT PLANNING_PK PRIMARY KEY (ID_PLANNING),
    CONSTRAINT PLANNING_FK_EVENT FOREIGN KEY (ID_EVENT) REFERENCES EVENEMENT(ID_EVENT)
);

CREATE SEQUENCE PLANNING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE OR REPLACE TRIGGER PLANNING_BI
BEFORE INSERT ON PLANNING
FOR EACH ROW
WHEN (NEW.ID_PLANNING IS NULL)
BEGIN
  SELECT PLANNING_SEQ.NEXTVAL INTO :NEW.ID_PLANNING FROM DUAL;
END;
/

-- Indexes et petits ajustements
CREATE INDEX IDX_EVENEMENT_LIEUX ON EVENEMENT(LIEUX);
CREATE INDEX IDX_EMPLOYES_NOM ON EMPLOYES(NOM);

-- Quelques exemples d'insertion (optionnel)
-- INSERT INTO EMPLOYES (NOM, PRENOM, POSTE, CONTRAT, SALAIRE) VALUES ('Doe', 'John', 'Responsable', 'CDD', 2000);
-- COMMIT;

-- Fin du script

-- Instructions d'exécution :
-- 1) Se connecter à Oracle en tant qu'utilisateur ayant les droits (ou en tant que SOUMAYA si vous voulez créer dans ce schéma) via SQL*Plus / SQL Developer.
-- 2) Exécuter ce script (ex: @create_summerclub.sql).
-- 3) Vérifier la correspondance des noms (SOUMAYA vs SummerClub DSN). Le DSN "SummerClub" doit pointer vers la base/schéma où ces tables ont été créées.
