-- Script pour corriger la table PLANNING
-- Exécutez ce script dans SQL Developer ou SQL*Plus

-- 1. Supprimer l'ancienne table si elle existe (et les contraintes)
DROP TRIGGER PLANNING_BI;
DROP SEQUENCE PLANNING_SEQ;
DROP TABLE PLANNING CASCADE CONSTRAINTS;

-- 2. Créer la nouvelle table PLANNING avec les bonnes colonnes
CREATE TABLE PLANNING (
    ID_PLANNING   NUMBER NOT NULL,
    SALLE         NUMBER NOT NULL,
    "DATE"        DATE NOT NULL,           -- "DATE" entre guillemets car c'est un mot réservé
    HEURE_DEBUT   TIMESTAMP NOT NULL,
    HEURE_FIN     TIMESTAMP NOT NULL,
    STATUT        VARCHAR2(50),
    TYPE_ACTIVITE VARCHAR2(100),
    CONSTRAINT PLANNING_PK PRIMARY KEY (ID_PLANNING),
    CONSTRAINT CHK_HEURE CHECK (HEURE_FIN > HEURE_DEBUT)
);

-- 3. Créer la séquence pour l'auto-incrémentation
CREATE SEQUENCE PLANNING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 4. Créer le trigger pour l'auto-incrémentation de l'ID
CREATE OR REPLACE TRIGGER PLANNING_BI
BEFORE INSERT ON PLANNING
FOR EACH ROW
WHEN (NEW.ID_PLANNING IS NULL)
BEGIN
  SELECT PLANNING_SEQ.NEXTVAL INTO :NEW.ID_PLANNING FROM DUAL;
END;
/

-- 5. Ajouter quelques données de test
INSERT INTO PLANNING (SALLE, "DATE", HEURE_DEBUT, HEURE_FIN, STATUT, TYPE_ACTIVITE)
VALUES (101, SYSDATE, TO_TIMESTAMP('2025-11-11 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        TO_TIMESTAMP('2025-11-11 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Confirme', 'Yoga');

INSERT INTO PLANNING (SALLE, "DATE", HEURE_DEBUT, HEURE_FIN, STATUT, TYPE_ACTIVITE)
VALUES (102, SYSDATE, TO_TIMESTAMP('2025-11-11 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        TO_TIMESTAMP('2025-11-11 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Non Confirme', 'Natation');

INSERT INTO PLANNING (SALLE, "DATE", HEURE_DEBUT, HEURE_FIN, STATUT, TYPE_ACTIVITE)
VALUES (103, SYSDATE+1, TO_TIMESTAMP('2025-11-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        TO_TIMESTAMP('2025-11-12 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Confirme', 'Tennis');

COMMIT;

-- Vérification
SELECT * FROM PLANNING;
